<?php

namespace PL\FacturationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CarnetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarnetRepository extends EntityRepository
{

  public function carnetStatutFilterRead($val){
    //renvoi liste ordonnée du carnet filtrée sur un statut $val
    return $this
      ->createQueryBuilder('c')
      ->orderBy('c.nomCar','ASC')
      ->leftJoin('c.statut', 'statut')
      ->addSelect('statut')
      ->where('statut.libSta = :val')
      ->setParameter('val',$val)


      ->getQuery()
      ->getResult()
      ;
  }

  public function myFindAll(){
    return $this
      ->createQueryBuilder('c')
      ->orderBy('c.datCar','ASC')
      ->getQuery()
      ->getArrayResult()
      ;
  }
}
