<?php

namespace PL\FacturationBundle\Entity;

/**
 * CompteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompteRepository extends \Doctrine\ORM\EntityRepository
{
  public function findCompteByCarnet($value){
    $qb = $this->createQueryBuilder('c');
    $qb
      ->where('c.carnet = :value')
      ->setParameter('value',$value)
      ;
  return  $qb
    ->getQuery()
    ->getSingleResult();
  }

  public function findCompteByType($value){
    $qb = $this->createQueryBuilder('c');
    $qb
      ->where('c.typCom = :value')
      ->setParameter('value',$value)
      ;
      return  $qb
        ->getQuery()
        ->getSingleResult();
  }

}
