<?php

namespace PL\FacturationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DevisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DevisRepository extends EntityRepository
{
  public function indexDevis($bool,$drtDev){
    // devis non archivés (bool = false)
    $qb = $this->createQueryBuilder('d');
    $qb
      ->Join('d.carnet','carnet')
      ->addSelect('carnet')
      ->Join('d.user','user')
      ->addSelect('user')
      ->where('d.arcDev = :bool')
      ->setParameter('bool',$bool)
      ->andwhere('d.drtDev = :drtDev')
      ->setParameter('drtDev',$drtDev)
      ->orderBy('d.datDev','DESC')
      ;
  return  $qb
    ->getQuery()
    ->getArrayResult();
  }

}
