<?php

namespace PL\FacturationBundle\Entity;

/**
 * FactureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FactureRepository extends \Doctrine\ORM\EntityRepository
{
  public function listFacture($bool,$drtFac){
    // facture non archivés ($bool = false)

    $qb = $this->createQueryBuilder('f');
    $qb
      ->Join('f.carnet','carnet')
      ->addSelect('carnet')
      ->where('f.arcFac = :bool')
      ->andwhere('f.drtFac = :drtFac')
      ->Join('f.devis','devis')
      ->addSelect('devis')
      ->Join('f.user','user')
      ->addSelect('user')
      ->setParameter('bool',$bool)
      ->setParameter('drtFac',$drtFac)
      ->orderBy('f.datFac','DESC')
      ;
  return  $qb
    ->getQuery()
    ->getArrayResult();
  }

  public function oneFacture($id){
    $qb = $this->createQueryBuilder('f');
    $qb
      ->Join('f.carnet','carnet')
      ->addSelect('carnet')
      ->where('f.id = :id')
      ->setParameter('id',$id)
      ;
  return  $qb
    ->getQuery()
    ->getResult();
  }
}
