<?php

namespace PL\FacturationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FamilleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FamilleRepository extends EntityRepository
{
  public function devisCreate($drtFam){
    $qb = $this->createQueryBuilder('f');
    $qb
      ->join('f.produits', 'produits')
      ->addSelect('produits')
      ->where('f.drtFam = :drtFam')
      ->setParameter('drtFam',$drtFam)
      ->orderBy('f.libFam','ASC')
    ;
    return $qb
      ->getQuery()
      ->getArrayResult();
  }

  public function familleIndex(){
    $qb = $qb = $this->createQueryBuilder('f');
    $qb
      ->join('f.user','user')
      ->addSelect('user')
    ;
    return $qb
      ->getQuery()
      ->getArrayResult();
  }
}
