<?php

namespace PL\FacturationBundle\Entity;

/**
 * MouvementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MouvementRepository extends \Doctrine\ORM\EntityRepository
{
  public function findMouvementByCompte($id){
    $qb = $this->createQueryBuilder('m');
    $qb
      ->leftJoin('m.compte','compte')
      ->addSelect('compte')
      ->leftJoin('m.ecriture','ecriture')
      ->addSelect('ecriture')
      ->where('compte.id = :id')
      ->setParameter('id',$id)
      ;
      return  $qb
        ->getQuery()
        ->getArrayResult();
  }


  public function findCreMouByDate($typCom,$start,$end,$drtFac){
    $expr1="Solde facture";
    $expr2="Règlement partiel";

    $qb = $this->createQueryBuilder('m');
    $qb
      ->Join('m.compte','compte')
      ->addSelect('compte')
      ->Join('m.ecriture','ecriture','WITH','ecriture.libEcr LIKE :expr1 OR ecriture.libEcr LIKE :expr2')
      ->addSelect('ecriture')
      ->Join('ecriture.facture','facture','WITH','facture.drtFac = :drtFac')
      ->addSelect('facture')
      ->where('compte.typCom = :typCom')
      ->setParameter('typCom',$typCom)
      ->andWhere('ecriture.datEcr BETWEEN :start AND :end')
      ->setParameter('start', $start)
      ->setParameter('end',  $end)
      ->andwhere('m.debMou > 0')
      ->setParameter('expr1','%'.$expr1.'%')
      ->setParameter('expr2','%'.$expr2.'%')
      ->setParameter('drtFac',$drtFac)
      ->orderBy('ecriture.datEcr', 'ASC');
      ;
      return  $qb
        ->getQuery()
        ->getArrayResult();
  }

  public function findMouvementByFacture($id,$idCarnet){
    $qb = $this->createQueryBuilder('m');
    $qb

    ->leftJoin('m.compte','compte')
    ->addSelect('compte')
    ->leftJoin('compte.carnet','carnet')
    ->addSelect('carnet')
      ->leftJoin('m.ecriture','ecriture')
      ->addSelect('ecriture')
      ->leftJoin('ecriture.facture','facture')
      ->addSelect('facture')
      ->where('facture.id = :id')
      ->andWhere('carnet.id = :idCarnet')
      ->setParameter('id',$id)
      ->setParameter('idCarnet',$idCarnet)

      ;
      return  $qb
        ->getQuery()
        ->getArrayResult();
  }

}// END CLASS
