<?php

namespace PL\FacturationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitRepository extends EntityRepository
{
    public function listProduits(){
      $qb = $this->createQueryBuilder('p');

      return $qb
        ->getQuery()
        ->getResult();
    }

    public function produitIndex(){
      $qb = $qb = $this->createQueryBuilder('p');
      $qb
        ->join('p.user','user')
        ->addSelect('user')
        ->join('p.infoproduit','infoproduit')
        ->addSelect('infoproduit')
        ->join('p.famille','famille')
        ->addSelect('famille')
      ;
      return $qb
        ->getQuery()
        ->getArrayResult();
    }

}
