<?php

namespace PL\FacturationBundle\Entity;

/**
 * ProduitFactureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitFactureRepository extends \Doctrine\ORM\EntityRepository
{
  public function readProduitFacture($id){
    $qb = $this->createQueryBuilder('pf');
    $qb
      ->Join('pf.produit','produit')
      ->addSelect('produit')
      ->Join('produit.infoproduit','infoproduit')
      ->addSelect('infoproduit')
      ->Join('pf.facture','facture')
      ->addSelect('facture')
      ->Join('facture.carnet','carnet')
      ->addSelect('carnet')
      ->Join('facture.user','user')
      ->addSelect('user')
      ->where('facture.id = :id')
      ->setParameter('id',$id)
      ;
      return  $qb
        ->getQuery()
        ->getArrayResult();
  }

}
